### ISSUE TITLE
MBARS.py line 291 raising SciPy FutureWarning

### ISSUE THREAD

**Issue by avivleecohen** [dhood14/MBARS#5]
There is a change in Scipy Mode. MBARS is now rising a warning saying:

"FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  plat = sps.mode(image.compressed())"
  
This occurs in line 291 in MBARS.py. Need to add 'keepdim' parameter (True/False) to avoid this warning in the future.

**Comment by dhood14** [comment]
Resolved, keepdims parameter added
